Prevent GreenletExit exceptions (and improve shutdown time) when shutting down with active keepalive connections
reddit/baseplate.py pull request #1009
Opened 2024-10-27 02:19 UTC by chriskuehl

<TODO>

2024-10-28 14:06 UTC, redloaf approved these changes

2024-10-28 20:38 UTC, mjbonifacio approved these changes
I'm informed and this appears sensible -- excited to try it. I wouldn't consider my approval authoritative as I don't think I'd be able to foresee other issues this might cause.

2024-11-03 00:00 UTC, salomon-smekecohen requested changes
I believe the way the `pywsgi` and `event` modules are accessed will cause issues.
<img width="245" alt="Screenshot 2024-11-02 at 6 00 49 PM" src="https://github.com/user-attachments/assets/618c2ddc-1633-433d-82ea-7c444f08e851">

2024-11-03 00:00 UTC, salomon-smekecohen commented on baseplate/server/wsgi.py
> +    shutdown_event: gevent.event.Event
gevent.event is a module up until recently. So this will be incompatible with a lot of gevent versions, even in fairly up-to-date repositories.

consider:

`from gevent import event`
and
`event.Event`

<img width="661" alt="Screenshot 2024-11-02 at 5 56 15 PM" src="https://github.com/user-attachments/assets/ad06192f-30fc-4448-9c6f-49ce3114447d">

2024-11-03 00:00 UTC, salomon-smekecohen commented on tests/integration/requests_tests.py
> +        server: gevent.pywsgi.WSGIServer
`pywsgi` also has the same issue.

2024-11-14 01:57 UTC, chriskuehl commented on baseplate/server/wsgi.py
> +    shutdown_event: gevent.event.Event
I think some lucky import side effects are preventing this from being an issue with how the code is currently written (it still imports for me with gevent 23.9.1 which is the oldest we support), but good idea to fix this since it's definitely fragile.

2024-11-14 17:23 UTC, merged

2024-11-14 17:25 UTC, salomon-smekecohen commented
ty! sorry for not re-reviewing quickly here