Baseplate health check v2 take 2
reddit/baseplate.py pull request #468
Opened 2020-07-17 22:04 UTC by fishy

Revert is_healthy endpoint defined in BaseplateService, and add health
check v2 into BaseplateServiceV2, and deprecate BaseplateService.

The healthcheck binary is switched to BaseplateServiceV2. It still works
with thrift services using BaseplateService.

2020-07-17 22:11 UTC, fishy commented
👓 @spladug @pacejackson

2020-07-17 22:35 UTC, fishy commented on baseplate/thrift/baseplate.thrift
> +service BaseplateServiceV2 {
Or maybe just `BaseplateService2`, not sure which one do y'all prefer.

2020-07-21 16:56 UTC, pacejackson approved these changes
V2 seems fine to me

2020-07-21 17:05 UTC, fishy commented
:haircut: Added an integration test to make sure that v2 health check client works with v1 server.

2020-07-21 18:14 UTC, spladug requested changes
looks great. thanks for the tests, that really improves confidence this is non-breaking and continues to be going forward. only thing is making the test suite a little less duplicated there.

2020-07-21 18:14 UTC, spladug commented on tests/integration/thrift_healthcheck_tests.py
> +        reload(socket)
this feels like a ton of duplication. could these be parameterized in the original module and either imported here or the test suite below just moved there? (i lean towards the latter as this is just a subset of thrift integration tests)

2020-07-21 20:25 UTC, spladug approved these changes

2020-07-21 20:25 UTC, merged