redis_cluster: add moar timeouts
reddit/baseplate.py pull request #605
Opened 2021-07-28 18:16 UTC by jerroydmoore

- Add support for the options socket_timeout and socket_connect_timeout.
- Set socket_timeout and socket_connection_timeout to timeout's value,
  if and only if, these weren't already set.

2021-07-28 19:00 UTC, FranGM approved these changes

2021-07-28 19:41 UTC, bradengroom requested changes
Can you add docs in the function docstring? This helps generate docs [here](https://baseplate.readthedocs.io/en/stable/api/baseplate/clients/redis_cluster.html?#baseplate.clients.redis_cluster.cluster_pool_from_config).

2021-07-28 19:59 UTC, spladug requested changes
lgtm modulo docs like @bradengroom pointed out. especially important to document that `timeout` will propagate to the other two settings if not explicitly set.

2021-07-28 21:33 UTC, bradengroom approved these changes

2021-07-28 21:53 UTC, spladug approved these changes
ty!

2021-07-29 23:58 UTC, kylelemons approved these changes

2021-08-04 22:11 UTC, merged