Redis client changes: Add retries
reddit/baseplate.py pull request #614
Opened 2021-08-26 18:07 UTC by FranGM

2021-08-26 18:18 UTC, bradengroom commented on baseplate/clients/redis.py
> +            except Exception:
I think I'd be hesitant to catch all exceptions here. You probably only want to retry certain failures, right? For example, if I have a bug in my code and I try to `SUNION` on a non-set filed, I'll get an error like the following:
```
127.0.0.1:6379> SET foo 5
OK
127.0.0.1:6379> SUNION foo
(error) WRONGTYPE Operation against a key holding the wrong kind of value
```

That's not going to work no matter how many times I retry.

2021-08-26 18:28 UTC, bradengroom requested changes
I'm concerned that this is pretty different from how we do retries elsewhere in baseplate.py and doesn't leave the dev with much control over how retries are performed. What if I want a certain retry policy in one location, but a totally different retry policy in a different location. The `MAX_RETRIES` and `MAX_RETRY_WAIT_MS` values are not configurable.

I think I would prefer a solution that doesn't really take over like this, but instead makes it easier for devs to add retries when and how they want. Today, baseplate supports this with a `retrying` context manager on thrift clients. So you can do something like this:
````
with context.my_service.retrying(attempts=3, budget=5, backoff=.5) as svc:
    svc.some_method()
````

These inputs to `retrying` are used to create a [`RetryPolicy`](https://baseplate.readthedocs.io/en/stable/api/baseplate/lib/retry.html).

It looks like we currently don't support the same `retrying` context manager on redis clients. What if we did that instead?

2021-08-26 18:33 UTC, FranGM commented on baseplate/clients/redis.py
> +            except Exception:
that command won't get retried, because it's not considered a retriable command. I'm happy to switch that to just catching the same exceptions we filter for the non-pipeline case, but it feels silly because the client will only raise the first exception within the pipeline, so filtering doesn't do much for you.

2021-08-26 18:41 UTC, FranGM commented
Sorry, didn't get to add more context after creating this PR. One of the main motivations behind this PR is to not require any changes to existing code or just minimal changes, and to still be as close as possible to a vanilla Redis client.

Adding a new context manager to help configure retry behaviour might make this difficult, not to mention that `pipeline` is already a context manager, which can make things confusing. (Also note that for every pipeline execution we can individually enable or disable retries, so we could also tweak number of retries, etc)

2021-08-26 23:59 UTC, spladug requested changes
Can you explain a bit more why we want transparent retries without requiring code changes to get them? I thought we were generally shying away from that kind of magic so it feels weird to add it here.

2021-08-26 23:59 UTC, spladug commented on baseplate/clients/redis.py
> +            except Exception:
The problem with catching `Exception` is that if there's a legit bug (e.g. out-of-bounds indexing an array) we catch that too. For library code, that's almost never the right answer. So we should definitely find a more tightly scoped catch here. It doesn't have to check subtypes like in the other path but not catching the base Exception is important.

2021-08-26 23:59 UTC, spladug commented on baseplate/clients/redis.py
> +        while retries < MAX_RETRIES:
fwiw there's a helper in baseplate for this sorta logic https://baseplate.readthedocs.io/en/stable/api/baseplate/lib/retry.html

2021-08-26 23:59 UTC, spladug commented on baseplate/clients/redis.py
> +class RetryStats:
since all the methods are static/class level, is there any value in this being a class?

2021-08-27 15:44 UTC, MelissaCole commented
:running_woman: looks like others have this handled

2021-09-01 11:20 UTC, FranGM commented
I'm going to close this for now as I think we're going to want to revisit the general approach not just in terms of retries, but also with the concept of having a shared connection pool across the whole context

2021-09-01 11:20 UTC, closed without merging