sqlalchemy: limit statement tag length
reddit/baseplate.py pull request #615
Opened 2021-08-26 21:44 UTC by curioussavage

related to https://github.com/reddit/baseplate.py/pull/613

I logged some spans and saw that the ORM was generating a statement that grows with the length of a list of ids. I need to change that query but it still seems like it could be a good idea to limit what is allowed.

We could also log a warning in when binary annotations are created on the span with really long strings too.

2021-08-27 17:17 UTC, spladug requested changes
Cool! That makes sense. I think 100 might be a bit intense though. I have regular queries in my app that are 400~ characters of just SQL -- not even the parameters. How about 1024 as a limit?

2021-08-27 17:17 UTC, spladug commented on baseplate/clients/sqlalchemy.py
>          span.set_tag("statement", statement)
```suggestion
        span.set_tag("statement", statement[:100])
```

It's safe to just truncate without checking. `"foo"[:100] == "foo"`.

2021-08-27 18:46 UTC, kylelemons approved these changes

2021-08-27 18:46 UTC, kylelemons commented on baseplate/clients/sqlalchemy.py
>          span.set_tag("statement", statement)
🔕 on the other hand, that's magical and someone in the future might not know about that behavior and be confused.

You might also want to say `statement = statement[:100] + "..."` when you're truncating so it's clear that some of the query is missing.   In the case where it happens to truncate it, say, right before the WHERE clause, having this could really aid in keeping confusion down.

2021-08-27 20:21 UTC, spladug commented on baseplate/clients/sqlalchemy.py
>          span.set_tag("statement", statement)
yeah fair point about the ellipsis to make it clear it was truncated (or even `[AND %d MORE BYTES]` or something)

2021-12-06 23:04 UTC, curioussavage commented
I'm sorry but I just realized This PR got left hanging. Fixed up with the suggestions.

2021-12-07 19:18 UTC, curioussavage commented
tried upgrading typed-ast after CI failed. That didn't work so I added a commit removing the line pinning the version so PIP could resolve it.

2021-12-07 23:20 UTC, spladug approved these changes
lgtm, thanks! it looks like a bunch of extra commits made it onto the branch though. can you make sure to clean those out before merging please?

2021-12-07 23:49 UTC, merged