Extend support for environment variable expansion
reddit/baseplate.py pull request #622
Opened 2021-09-26 20:30 UTC by alisaifee

# Description
Use the [expandvars](https://github.com/sayanarijit/expandvars/) library to support different bash parameter expansion methods.

This allows use cases such as providing defaults, offsets and indirection.

To retain compatibility any error in expansion (whether due to missing variable, or invalid syntax) will not raise but simply return the config value as declared in the config file - while logging a warning.

`pytest-check` was added to development dependencies to use multiple assertions per test case

2021-09-27 16:55 UTC, kylelemons requested changes
This needs to be discussed as a a baseplate.spec change first.  The environment substitution is intended to handle some very specific cases where the value must come from the Kubernetes Downward-Facing API, it is not intended to be used for situational overrides, etc.  Among other things, this is likely to severely complicate the cross-language compatibility story.

2021-09-27 19:15 UTC, spladug requested changes
cool! thanks for submitting this. let's chat it through in the spec and make sure it fits the goal of our config systems and it's something we want to support across all languages.

2021-09-27 21:22 UTC, MelissaCole commented
:running_woman: to clear my salon

2021-09-29 21:01 UTC, alisaifee commented
I'lll close this for now since this doesn't appear to be inline with the spec.

2021-09-29 21:01 UTC, closed without merging