Extend SecretsStore to support Vault CSI
reddit/baseplate.py pull request #625
Opened 2021-10-16 02:05 UTC by praxist

- SecretsStore reworked to support multiple filewatchers given a directory instead of a secret file
- Added parsing classes to separate some of the Vault secret format from the SecretsStore, since format is different between the Vault secrets fetcher and Vault CSI
- More information on vault-csi: https://www.vaultproject.io/docs/platform/k8s/csi
- Add deprecation notice for Vault-specific functions in SecretsStore

Reddit-only design link: https://docs.google.com/document/d/1nQ8Fhh-WQ4egtIMG_FZzW-dvqAEObsp-onKrQzEn9CA/edit#
This change should be completely transparent for services sticking with secrets fetchers. For those wanting to use vault-csi, they will have to do the following:
- .ini change to `secrets.path = some_directory`
- .ini change to `secrets.provider = vault_csi`
- change references of secret paths in code to just the secret name itself.

Note for testing: I moved the existing test suite to its own file and duplicated the tests in the context of SecretsStore using a dir with multiple secrets files vs a single file - I think this provides better coverage though I'm open to collapsing it back down to one file.

2021-10-18 17:56 UTC, spladug requested changes
Cool! Thanks for doing this. I think the biggest thing is it'd really be best not to be branching in every function like that but instead use separate classes for each implementation. We'll have to keep an eye on performance and consider our options if checking all those mtimes is too slow. Excited to see the CSI provider replace the secrets fetcher soon!

2021-10-18 17:56 UTC, spladug commented on baseplate/lib/secrets.py
> +            for root, _, files in os.walk(path):
Are there ever going to be subdirectories? or just a flat directory of files? In the latter case it'd be simpler to use `os.listdir` or `Path(...).iterdir()`.

Do we need to worry about new files being created later on? (i.e. new secrets) If so we'd want to do this directory listing operation more than once.

2021-10-18 17:56 UTC, spladug commented on baseplate/lib/secrets.py
> +        self.path_type = "dir" if os.path.isdir(path) else "file"
This is a pretty big smell: we shouldn't have to branch about this in all the places we do below. But instead the `secrets_store_from_config` should return one of two concrete implementations of SecretsStore depending on which kind of secrets storage we're dealing with.

2021-10-18 17:56 UTC, spladug commented on baseplate/lib/secrets.py
> +                    file_path = os.path.relpath(os.path.join(root, f), path)
[pathlib](https://docs.python.org/3/library/pathlib.html) makes this kind of path manipulation much easier on the eye.

2021-10-18 17:56 UTC, spladug commented on baseplate/lib/secrets.py
> +        warn_deprecated("get_vault_url is deprecated and will be removed in the future.")
```suggestion
        warn_deprecated("get_vault_url is deprecated and will be removed in v3.0.")
```

2021-10-18 17:56 UTC, spladug commented on baseplate/lib/secrets.py
> -    @cached_property
note: this is going to be a performance regression for the single-file use case. `@cached_property` replaces itself with the cached data after the first lookup so we do fewer dict lookups when re-using the property.

2021-10-18 17:56 UTC, spladug commented on baseplate/lib/secrets.py
> +        return self._cached_data[filename]
won't this raise a KeyError if the data's not cached? 

something like this would be more efficient in lookups since we don't hit the dictionary multiple times:

```suggestion
        try:
            result = self._cached_data[filename]
        except KeyError:
            result = super()._get_data(filename)
            self._cached_data[filename] = result
        return result
```

(though note this is still slower than `@cached_property` for the single file case)

2021-10-18 17:56 UTC, spladug commented on baseplate/lib/secrets.py
> +        return data["data"]
These don't need to be classes. It can just be a function:

```suggestion
SecretParser = Callable[[Dict[str, Any], str], Dict[str, str]]


def parse_secrets_fetcher(data: Dict[str, Any], secret_path: str = "") -> Dict[str, str]:
    try:
        return data["secrets"][secret_path]
    except KeyError:
        raise SecretNotFoundError(secret_path)


def parse_vault_csi(data: Dict[str, Any], secret_path: str = "") -> Dict[str, str]:
    return data["data"]
```

2021-10-18 17:56 UTC, spladug commented on baseplate/lib/secrets.py
> -    @cached_property
we'll also need to keep an eye on the multi-file applications' performance. now they'll need to do multiple stat calls per request to make sure they're fresh when before it was just one.

we have a couple options should it prove too slow: cache for longer, or switch to inotify.

2021-10-18 23:29 UTC, kylelemons requested changes
It looks like spladug has this review, but from my perspective I think it would be useful for the PR / commit to summarize the high-level considerations that need to be made in the transition.  Notably, this will need to be mimicked in the Go and TypeScript baseplate libraries, so having a concise description of the changes are that motivate the change would be useful so that the implementation doesn't have to be the canonical documentation of how it works.

2021-10-19 03:20 UTC, praxist commented on baseplate/lib/secrets.py
> +            for root, _, files in os.walk(path):
yep, there can be subdirectories if the objectName has `/`s in them. e.g. trying to use `secret/blah` instead of `blah` would create an additional directory `secret`.

2021-10-19 03:21 UTC, praxist commented on baseplate/lib/secrets.py
> +            for root, _, files in os.walk(path):
second question - new files wouldn't be created unless a change is made to the deploy config to add additional objects.

2021-10-19 06:31 UTC, praxist commented on baseplate/lib/secrets.py
> +        return self._cached_data[filename]
decided to use `.get()` rather than the try/except, I believe that's slightly more performant.

2021-10-19 06:33 UTC, praxist commented
Split the SecretsStore logic into 2 subclasses representing the file/directory implementations.

2021-10-20 20:28 UTC, spladug requested changes
awesome! final stretch. this is looking really good. just a couple final things.

2021-10-20 20:28 UTC, spladug commented on baseplate/lib/secrets.py
> +# pylint: disable=method-hidden,unused-argument
is `method-hidden` still necessary?

2021-10-20 20:28 UTC, spladug commented on baseplate/lib/secrets.py
>  class SecretsStore(ContextFactory):
I agree that making the base class into an interface would be ideal, but unfortunately we've got a lot of users that are directly instantiating this (mostly in test suites). So this is a breaking change. For now, we can make the FileSecretsStore the base class and make the swap out in v3.0. Does that sound OK?

2021-10-20 20:28 UTC, spladug commented on baseplate/lib/secrets.py
> +        self.parser = parser or parse_secrets_fetcher
This could probably just be a mandatory parameter. Or if not, maybe it'd make more sense to default to `parse_vault_csi` since that's more likely to be used with this subclass than the other parser.

2021-10-20 20:28 UTC, spladug commented on baseplate/lib/secrets.py
> +        return self._cached_data[filename]
This is still looking up the value in the hash twice for each entry (the get() and the []). Is there a reason to prefer this over the try/except method I commented previously?

2021-10-20 20:28 UTC, spladug commented on baseplate/lib/secrets.py
> +    if os.path.isdir(options.path):
Iiiinteresting. I'm curious why we'd want to do this separately from the branching on provider? It seems like it might lead to easier accidental misconfiguration.

2021-10-20 20:28 UTC, spladug commented on baseplate/lib/secrets.py
> +    :param provider: The secrets provider. Defaults to 'vault'.
maybe good to document the alternative too?

2021-10-21 04:00 UTC, praxist commented on baseplate/lib/secrets.py
> +        self.parser = parser or parse_secrets_fetcher
set to mandatory param

2021-10-21 04:01 UTC, praxist commented on baseplate/lib/secrets.py
> +        return self._cached_data[filename]
you're right - switched to try/except.

2021-10-21 04:01 UTC, praxist commented on baseplate/lib/secrets.py
> +    if os.path.isdir(options.path):
was originally trying to decouple the path/file secrets store from any vault references, but that might have been unnecessary.

2021-10-21 04:36 UTC, praxist commented on baseplate/lib/secrets.py
>  class SecretsStore(ContextFactory):
ok, collapsed FileSecretsStore back to SecretsStore (hope I'm assuming correctly that's what you meant?)

2021-10-21 17:35 UTC, spladug approved these changes
looks great. thank you!

2021-10-21 17:35 UTC, spladug commented on baseplate/lib/secrets.py
> +                )
:no_bell: this can be fully written with pathlib to simplify a bit

```suggestion
        root = Path(path)
        for p in root.glob("**"):
            file_path = str(p.relative_to(root))
            self._filewatchers[file_path] = FileWatcher(
                file_path, json.load, timeout=timeout, backoff=backoff
            )
```

2021-10-21 18:17 UTC, praxist commented on baseplate/lib/secrets.py
> +                )
oh yeah, that looks much nicer, awesome

2021-10-25 21:03 UTC, praxist commented
@spladug / @kylelemons ready to merge - will squash with the following commit message:
```
Extend SecretsStore to support Vault CSI

This change adds an additional way to load secrets besides the existing secrets fetcher:
- When vault.provider is set to vault_csi, vault.path will be assumed to be a directory containing individual files representing secrets, rather than a single file containing every secret.
- Vault CSI loads secrets automatically into these files on pod startup, so no additional sidecar is required.
- Secrets are written to files in a different JSON format
- Each secrets file has its own filewatcher representation with per-request caching behavior preserved

Implementation details:
- Add DirectorySecretsStore subclass of SecretsStore supporting multiple filewatchers
- Duplicate SecretsStore unit tests in the context of DirectorySecretsStore
- Modify secrets_store_from_config to return SecretsStore or DirectorySecretsStore based off vault.provider
- Split out vault-specific file parsing logic into functions outside of SecretsStore
- Add deprecation notice for get_vault_url, get_vault_token in SecretsStore
```

2021-10-26 23:31 UTC, kylelemons approved these changes

2021-10-26 23:54 UTC, merged