feat(Span): Allow span to be created with tags in a context manager
reddit/baseplate.py pull request #667
Opened 2022-05-03 20:42 UTC by Xaelias

This is relevant to https://github.com/reddit/baseplate.py/pull/663.

As the title says, the goal is to be able to define Spans with a list of tags before the Span itself is started.

2022-05-03 21:04 UTC, mterwill approved these changes
Thank you!

2022-05-03 21:04 UTC, mterwill commented on tests/unit/core_tests.py
> +            )
🔕 nit: I usually tend towards being explicit with this kind of stuff in tests, accidentally checked that `None == None` one too many times 🤷‍♂️ 😅 

```suggestion
            mock_observer.on_set_tag.assert_has_calls([
                mock.call("k1", "v1"),
                mock.call("k2", "v2"),
            ])
```

2022-05-04 15:40 UTC, Xaelias commented on tests/unit/core_tests.py
> +            )
Updated :-) Thanks for calling me out on my laziness :p

2022-05-04 15:59 UTC, mterwill approved these changes

2022-05-05 19:18 UTC, KTAtkinson requested changes

2022-05-05 19:18 UTC, KTAtkinson commented on baseplate/__init__.py
> +        """This allows us to set tags in a Span before starting it in a context manager.
Please write documentation in an authoritative voice:
```suggestion
        """Declare a set of tags to be added to a span before starting it in the context manager.
```

2022-05-09 21:19 UTC, KTAtkinson approved these changes

2022-05-10 15:07 UTC, merged