[BASE-36] Implement AMQP Producer (kombu) prometheus metrics
reddit/baseplate.py pull request #691
Opened 2022-06-24 19:25 UTC by Xaelias

## 🧪 Testing Steps / Validation
examples.ini
```
kombu_p.hostname = localhost
kombu_p.exchange_type = topic
kombu_p.exchange_name = test
```

baseplate app
```
with context.span.make_child('kombu', local=True, component_name='stuff') as span:
    try:
        r = span.context.kombu_p.publish("msg", routing_key="123")
    except Exception as e:
        pass
```

/metrics
NOTE: this topic doesn't exist... but as far as I can tell, by default, Kombu doesn't not raise this as an error and reports a success
```
# HELP amqp_producer_message_processed_total Multiprocess metric
# TYPE amqp_producer_message_processed_total counter
amqp_producer_message_processed_total{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/"} 1.0
# HELP amqp_producer_message_processing_seconds Multiprocess metric
# TYPE amqp_producer_message_processing_seconds histogram
amqp_producer_message_processing_seconds_sum{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/"} 0.013274467999999984
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.0001"} 0.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.00025"} 0.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.000625"} 0.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.0015625"} 0.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.00390625"} 0.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.009765625"} 0.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.0244140625"} 1.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.06103515625"} 1.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.152587890625"} 1.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.3814697265625"} 1.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="0.95367431640625"} 1.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="2.384185791015625"} 1.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="5.9604644775390625"} 1.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="14.901161193847656"} 1.0
amqp_producer_message_processing_seconds_bucket{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/",le="+Inf"} 1.0
amqp_producer_message_processing_seconds_count{amqp_address="localhost:None",amqp_exchange="topic",amqp_queue="test",amqp_success="true",amqp_virtual_host="/"} 1.0
```

## ✅ Checks

- [x] CI tests (if present) are passing
- [x] Adheres to code style for repo
- [x] Contributor License Agreement (CLA) completed if not a Reddit employee

2022-06-27 18:38 UTC, KTAtkinson requested changes

2022-06-27 18:38 UTC, KTAtkinson commented on baseplate/clients/kombu.py
> +PROCESSING_TIME = Histogram(
Should this be `AMQP_PROCESSING_TIME`, as Kombu can be used for more than just reading from AMQP queues?

2022-06-27 18:38 UTC, KTAtkinson commented on baseplate/clients/kombu.py
> +            "amqp_address": f"{self.connection.hostname}:{self.connection.port}",
It looks like these labels are being set for all consumers, not just AMQP ones.

2022-06-28 15:49 UTC, KTAtkinson approved these changes

2022-06-30 19:53 UTC, nsheaps commented on baseplate/clients/kombu.py
> +            "amqp_virtual_host": self.connection.virtual_host,
should this be added to the spec?

2022-06-30 19:58 UTC, nsheaps approved these changes
Updated [spec](https://github.snooguts.net/reddit/baseplate.spec/pull/51) based on this PR.

We can re-add pool stuff later if it's useful

2022-07-06 18:50 UTC, merged