Replaced isfunction & ismethod with isroutine
reddit/baseplate.py pull request #707
Opened 2022-07-15 15:52 UTC by TheRealVira

This pretty much returns exactly the same as before, but with the benefit of including C functions/methods. You can read more about that here:

https://stackoverflow.com/a/17019998/6901146

2022-07-15 16:50 UTC, KTAtkinson requested changes
Thank you for your contribution!

Please make sure CI passes.

2022-07-15 16:50 UTC, KTAtkinson commented on baseplate/clients/thrift.py
> +
```suggestion

```

2022-07-15 16:50 UTC, KTAtkinson commented on baseplate/clients/thrift.py
> -
Please avoid making unrelated whitespace changes.

2022-07-15 16:53 UTC, TheRealVira commented on baseplate/clients/thrift.py
> -
Ok undid all whitespace changes. 😅

2022-07-15 18:45 UTC, TheRealVira commented
@KTAtkinson so... I can't re-run the workflow since I am a "First-time contributor". Would you please do me the honors to approve the run?

2022-07-18 18:53 UTC, KTAtkinson approved these changes

2022-07-18 19:27 UTC, TheRealVira commented
What do you think? Shall I adapt the test cases? (:

2022-07-18 20:13 UTC, KTAtkinson requested changes
Approved the run but it looks like it failed :)

2022-07-19 16:14 UTC, TheRealVira commented
@KTAtkinson I have replaced `inspect` with `__dict__` - inspect apparently returns user-defined and built-in functions.

2022-07-19 23:20 UTC, KTAtkinson approved these changes

2022-07-20 09:36 UTC, TheRealVira commented
Awesome! @KTAtkinson you need anything more from my end for this PR? (: 

Btw I'd really appreciate an "Open Sorcerer" trophy [on my Reddit profile](https://www.reddit.com/user/butineedthatusername/)

2022-07-28 17:50 UTC, TheRealVira commented
💇‍♀️

2022-07-28 18:16 UTC, KTAtkinson commented
Nothing else needed from your end, we are working to get a critical feature out now, so I won't be able to release this for a bit.

2022-07-28 18:17 UTC, KTAtkinson approved these changes

2022-12-21 07:46 UTC, TheRealVira commented
💇‍♀️

2023-01-04 17:32 UTC, KTAtkinson approved these changes

2023-03-10 18:48 UTC, TheRealVira commented
hi @KTAtkinson it looks like @aba-ca-xi isn't available (anymore?). Could you please assign another reviewer?

2023-04-10 17:34 UTC, TheRealVira commented
@maeivysea maybe?

2023-07-29 15:29 UTC, TheRealVira commented
@KTAtkinson when merge?

2025-03-24 23:13 UTC, closed without merging