Issues/strgs 12
reddit/baseplate.py pull request #724
Opened 2022-08-02 22:46 UTC by kumaramit01

Closes # 

## 💸 TL;DR

## 📜 Details
[Design Doc]()

[Jira]()

## 🧪 Testing Steps / Validation

## ✅ Checks

- [ ] CI tests (if present) are passing
- [ ] Adheres to code style for repo
- [ ] Contributor License Agreement (CLA) completed if not a Reddit employee

2022-08-04 20:36 UTC, kumaramit01 commented on Dockerfile
> +RUN apt-get update -y
FYI -I needed to add these for the building the kafka connector -there were header files missing and connector could not be built without the librdkafka-dev

2022-08-08 19:10 UTC, nsheaps requested changes
Rejecting until we have agreement on the PR that this PR uses functionality from

2022-08-08 22:02 UTC, kylelemons requested changes
Pending internal agreement on design.

(please don't link to internal documents from public PRs)

2022-08-09 22:35 UTC, kumaramit01 commented
We are changing the way this particular feature will be implemented in infrared -thanks for looking at this PR, closing this PR.

2022-08-09 22:35 UTC, closed without merging